package Utils.OtherTool;

import java.util.Objects;

public class WordList {
    public static String getWord(int sort, String language) {
        if (Objects.equals(language, "English")) {
            if (sort == 0) return "Save and exit to menu";
            else if (sort == 1) return "'s world";
            else if (sort == 2) return "easy";
            else if (sort == 3) return "normal";
            else if (sort == 4) return "hard";
            else if (sort == 5) return "KeepInventory: True";
            else if (sort == 6) return "KeepInventory: False";
            else if (sort == 7) return "Difficulty: Peaceful";
            else if (sort == 8) return "Difficulty: Easy";
            else if (sort == 9) return "Difficulty: Normal";
            else if (sort == 10) return "Difficulty: Hard";
            else if (sort == 11) return "Music: ON";
            else if (sort == 12) return "Music: OFF";
            else if (sort == 13) return "If amount of worlds is above 12, some worlds may not be seen here";
            else if (sort == 14) return "Single-Player";
            else if (sort == 15) return "Muti-Player";
            else if (sort == 16) return "Quit Game";
            else if (sort == 17) return "FlatMC v0.4.0";
            else if (sort == 18) return "Made by 薄言EZ";
            else if (sort == 19) return " has already existed, please delete it";
            else if (sort == 20) return "You have already owned too many worlds, delete some";
            else if (sort == 21) return "Not available";
            else if (sort == 22) return "Click the button below to enter your world";
            else if (sort == 23) return "Couldn't find any world in your computer, try creating one";
            else if (sort == 24) return "Create new world";
            else if (sort == 25) return "Back to menu";
            else if (sort == 26) return "Inventory";
            else if (sort == 27) return "Blocks";
            else if (sort == 28) return "Tools";
            else if (sort == 29) return "Minerals";
            else if (sort == 30) return "Others";
            else if (sort == 31) return "You     Died";
            else if (sort == 32) return "Respawn";
            else if (sort == 33) return "Save and exit to menu";
            else if (sort == 34) return "Refresh";
            else if (sort == 35) return "Click the button below to enter server";
            else if (sort == 36) return "Couldn't find any server in your computer, try adding one";
            else if (sort == 37) return "If amount of servers is above 12, some servers may not be seen here";
            else if (sort == 38) return "Connecting to the server...";
            else if (sort == 39) return "Connected, starting the game";
            else if (sort == 40) return "Cannot connect to the server";
            else if (sort == 41) return "Back";
            else if (sort == 42) return "Link lost";
            else if (sort == 43) return "Linking timeout";
            else if (sort == 44) return "Disconnect";
            else if (sort == 45) return "You don't have the permission of this command";
            else if (sort == 46) return " left the game";
            else if (sort == 47) return " joined the game";
            else if (sort == 48) return " was teleported to ";
            else if (sort == 49) return "'s keepinventory set to ";
            else if (sort == 50) return "Time set to ";
            else if (sort == 51) return "'s gamemode set to ";
            else if (sort == 52) return "World difficulty set to ";
            else if (sort == 53) return "World has been saved";
            else if (sort == 54) return " was killed by command";
            else if (sort == 55) return "Server stopped";
            else if (sort == 56) return " has been oped";
            else if (sort == 57) return " has been deoped";
            else if (sort == 58) return " killed ";
            else if (sort == 59) return " fell to death";
            else if (sort == 60) return " choked to death";
            else if (sort == 61) return "'s brain was eaten by zombie";
            else if (sort == 62) return "Online Players";
            else if (sort == 63) return "Link failed: player with your name is online";
            else if (sort == 64) return " fell into the void";
            else if (sort == 65) return "Unknown command";
            else if (sort == 66) return "Time now: ";
            else if (sort == 67) return " block set to ";
            else if (sort == 68) return "Given ";
            else if (sort == 69) return " is not an available number or name";
            else if (sort == 70) return " is not an available number or mode";
            else if (sort == 71) return " is not an available difficulty level";
            else if (sort == 72) return "Location is out of the world's size";
            else if (sort == 73) return " is not an available number";
            else if (sort == 74) return " is not an available boolean";
            else if (sort == 75) return "Usage : ";
            else if (sort == 76) return "Error :  ";
            else if (sort == 77) return "player not exist or online";
            else if (sort == 78) return "Your Location: ";
            else if (sort == 79) return "Selected block Location: ";
            else if (sort == 80) return "Fps: ";
            else if (sort == 81) return "'s inventory was cleared";
            else if (sort == 82) return " was cleared with ";
            else if (sort == 83) return " is not an available entity name";
            else if (sort == 84) return " has summoned at ";
            else if (sort == 85) return "Gama set to: ";
            else if (sort == 86) return "Gama now: ";
            else if (sort == 87) return "Gravity set to: ";
            else if (sort == 88) return "Gravity now: ";
            else if (sort == 89) return " is not an available object";
            else if (sort == 90) return "Air resistance set to: ";
            else if (sort == 91) return "Air resistance now: ";
            else if (sort == 92) return "'s spawn point set to ";
            else if (sort == 93) return "World spawn point set to ";
            else if (sort == 94) return "You have been teleported to world spawn point";
            else if (sort == 95) return " wants to teleport to your position, the request will be canceled in 30s";
            else if (sort == 96) return "Accept: /tpaccept";
            else if (sort == 97) return "Deny: /tpdeny";
            else if (sort == 98) return "Your teleport request has been sent to ";
            else if (sort == 99) return "Your teleport request has been accepted";
            else if (sort == 100) return "Your teleport request has been denied";
            else if (sort == 101) return "You don't have any teleport request to solve";
            else if (sort == 102) return "Your teleport request to ";
            else if (sort == 103) return "The teleport request from ";
            else if (sort == 104) return " has been canceled";
            else if (sort == 105) return "You cannot teleport to yourself";
            else if (sort == 106) return "You have accepted the teleport request";
            else if (sort == 107) return "You have denied the teleport request";
            else if (sort == 108) return " has been withdrawn";
            else if (sort == 109) return "Entered passwords differ";
            else if (sort == 110) return "Register success";
            else if (sort == 111) return "You can't use null as your password, change another one";
            else if (sort == 112) return "Login success";
            else if (sort == 113) return "Wrong password";
            else if (sort == 114) return "You still don't have a password, use /register to create one first";
            else if (sort == 115) return "Log in time out";
            else if (sort == 116) return "Please register by using /register password passwordAgain";
            else if (sort == 117) return "Please logging in by using /login password";
            else if (sort == 118) return "Home set successfully";
            else if (sort == 119) return "You have returned home";
            else if (sort == 120) return " whispered to you: ";
            else if (sort == 121) return "You have already logged in";
            else if (sort == 122) return "You have already registered";
            else if (sort == 123) return "You whispered to ";
            else if (sort == 124) return " : ";
            else if (sort == 125) return " was kicked out of game";
            else if (sort == 126) return " was banned";
            else if (sort == 127) return "You have been kicked out of game";
            else if (sort == 128) return "You IP address was banned";
            else if (sort == 129) return "Your account was banned";
            else if (sort == 130) return " was unbanned";
            else if (sort == 131) return "You can't do this in protected area";
            else if (sort == 132) return "Initializing world...";
        } else if (Objects.equals(language, "Chinese")) {
            if (sort == 0) return "保存并返回菜单";
            else if (sort == 1) return "的世界";
            else if (sort == 2) return "简单";
            else if (sort == 3) return "普通";
            else if (sort == 4) return "困难";
            else if (sort == 5) return "死亡后物品不掉落：开";
            else if (sort == 6) return "死亡后物品不掉落：关";
            else if (sort == 7) return "难度：和平";
            else if (sort == 8) return "难度：简单";
            else if (sort == 9) return "难度：普通";
            else if (sort == 10) return "难度：困难";
            else if (sort == 11) return "音乐：开";
            else if (sort == 12) return "音乐：关";
            else if (sort == 13) return "如果世界数目多于12，部分世界可能无法显示";
            else if (sort == 14) return "单人游戏";
            else if (sort == 15) return "多人游戏";
            else if (sort == 16) return "退出游戏";
            else if (sort == 17) return "我的世界2D版 v0.4.0";
            else if (sort == 18) return "薄言EZ制作";
            else if (sort == 19) return " 已经存在，请删除它再创建";
            else if (sort == 20) return "您的世界数目过多，请删除一些";
            else if (sort == 21) return "暂未开放";
            else if (sort == 22) return "点击下方按钮进入世界";
            else if (sort == 23) return "没有在您的电脑上找到任何世界，请尝试创建一个";
            else if (sort == 24) return "创建世界";
            else if (sort == 25) return "返回菜单";
            else if (sort == 26) return "物品栏";
            else if (sort == 27) return "方块";
            else if (sort == 28) return "工具";
            else if (sort == 29) return "矿物";
            else if (sort == 30) return "其它";
            else if (sort == 31) return "您 死 了";
            else if (sort == 32) return "重生";
            else if (sort == 33) return "保存并退出";
            else if (sort == 34) return "刷新";
            else if (sort == 35) return "点击下方按钮进入服务器";
            else if (sort == 36) return "没有在您的电脑上找到任何服务器，请尝试添加一个";
            else if (sort == 37) return "如果服务器数目多于12，部分服务器可能无法显示";
            else if (sort == 38) return "正在连接至服务器...";
            else if (sort == 39) return "连接成功，正在进入游戏";
            else if (sort == 40) return "无法连接至服务器";
            else if (sort == 41) return "返回";
            else if (sort == 42) return "链接丢失";
            else if (sort == 43) return "连接超时";
            else if (sort == 44) return "断开连接";
            else if (sort == 45) return "您没有使用此命令的权限";
            else if (sort == 46) return " 离开了游戏";
            else if (sort == 47) return " 加入了游戏";
            else if (sort == 48) return " 已被传送至 ";
            else if (sort == 49) return " 的死亡不掉落设为 ";
            else if (sort == 50) return "时间设置为：";
            else if (sort == 51) return " 的游戏模式设为 ";
            else if (sort == 52) return "世界难度设为 ";
            else if (sort == 53) return "世界已保存";
            else if (sort == 54) return " 死于指令";
            else if (sort == 55) return "服务器已关闭";
            else if (sort == 56) return " 已被设为管理员";
            else if (sort == 57) return " 已被撤去管理员";
            else if (sort == 58) return " 击败了 ";
            else if (sort == 59) return " 从高处跌落";
            else if (sort == 60) return " 窒息了";
            else if (sort == 61) return " 被僵尸吃掉了脑子";
            else if (sort == 62) return "在线玩家";
            else if (sort == 63) return "连接失败：相同名称玩家已在线";
            else if (sort == 64) return " 掉入了虚空";
            else if (sort == 65) return "未知的指令";
            else if (sort == 66) return "当前时间：";
            else if (sort == 67) return " 的方块已放置为 ";
            else if (sort == 68) return "给予 ";
            else if (sort == 69) return " 不是有效的数字或名称";
            else if (sort == 70) return " 不是有效的数字或模式";
            else if (sort == 71) return " 不是有效的难度等级";
            else if (sort == 72) return "目标位置超出世界大小";
            else if (sort == 73) return " 不是有效的数字";
            else if (sort == 74) return " 不是有效的布尔值";
            else if (sort == 75) return "用法：";
            else if (sort == 76) return "错误：";
            else if (sort == 77) return "玩家不存在或未在线";
            else if (sort == 78) return "您的坐标：";
            else if (sort == 79) return "选中方块坐标：";
            else if (sort == 80) return "当前帧率：";
            else if (sort == 81) return " 的背包已被清空";
            else if (sort == 82) return " 被清除了 ";
            else if (sort == 83) return " 不是有效的实体名";
            else if (sort == 84) return " 已生成在 ";
            else if (sort == 85) return "亮度设置为: ";
            else if (sort == 86) return "当前亮度: ";
            else if (sort == 87) return "重力设置为: ";
            else if (sort == 88) return "当前重力: ";
            else if (sort == 89) return " 不是有效的对象";
            else if (sort == 90) return "空气阻力设置为: ";
            else if (sort == 91) return "当前空气阻力: ";
            else if (sort == 92) return " 的重生点已设为 ";
            else if (sort == 93) return "世界重生点已设为 ";
            else if (sort == 94) return "您已被传送至世界重生点";
            else if (sort == 95) return " 想要传送到您的位置，该请求30秒后过期";
            else if (sort == 96) return "接受请求：/tpaccept";
            else if (sort == 97) return "拒绝请求：/tpdeny";
            else if (sort == 98) return "您的传送请求已发送给 ";
            else if (sort == 99) return "您的传送请求已被接受";
            else if (sort == 100) return "您的传送请求已被拒绝";
            else if (sort == 101) return "您没有待处理的传送请求";
            else if (sort == 102) return "您发送给 ";
            else if (sort == 103) return "来自 ";
            else if (sort == 104) return " 的传送请求因超时已被取消";
            else if (sort == 105) return "您不能传送到自己身边";
            else if (sort == 106) return "您已接受传送请求";
            else if (sort == 107) return "您已拒绝传送请求";
            else if (sort == 108) return " 的传送请求已被发送方撤回";
            else if (sort == 109) return "两次输入的密码不一致";
            else if (sort == 110) return "注册成功";
            else if (sort == 111) return "您不能用null作为您的密码，请更换一个再试";
            else if (sort == 112) return "登陆成功";
            else if (sort == 113) return "密码错误";
            else if (sort == 114) return "您还没有设置密码，请先使用/register注册账户";
            else if (sort == 115) return "登录超时";
            else if (sort == 116) return "您还没有注册，注册方式：/register 密码 重复密码";
            else if (sort == 117) return "请使用密码登录，登录方式：/login 密码";
            else if (sort == 118) return "家设置成功";
            else if (sort == 119) return "您已回家";
            else if (sort == 120) return " 悄悄对您说：";
            else if (sort == 121) return "您已经登录过了";
            else if (sort == 122) return "您已经注册过了";
            else if (sort == 123) return "您悄悄对 ";
            else if (sort == 124) return " 说：";
            else if (sort == 125) return " 被踢出了游戏";
            else if (sort == 126) return " 被封禁";
            else if (sort == 127) return "您被踢出了游戏";
            else if (sort == 128) return "您的IP已被封禁";
            else if (sort == 129) return "您的账户已被封禁";
            else if (sort == 130) return " 被解除封禁";
            else if (sort == 131) return "您不能在保护区内进行该操作";
            else if (sort == 132) return "正在初始化世界...";
        }
        return "null";
    }
}
